language: cpp

matrix:
  include:
    - os: linux

addons:
  apt:
    packages:
      - libsdl2-dev
      - fpc

script:
  - git clone https://github.com/ev1313/Pascal-SDL-2-Headers
  - fpc -Mtp -Fu./Pascal-SDL-2-Headers/ SJ3.PAS
